version: "3"
services: 
    app:
        container_name: app
        restart: always
        build: ./api
        ports:
            - "4000:4000"
        depends_on:
            - mongo
    admin:
        container_name: admin
        restart: always
        build: ./adminpannel
        ports:
            - "5000:5000"
        depends_on:
            - app
    client:
        container_name: client
        restart: always
        build: ./client
        ports:
            - "3000:3000"
        depends_on:
            - app
    mongo:
        container_name: mongo
        image: mongo
        restart: always
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"